# Generated by Django 2.0 on 2017-12-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=256)),
                ('misconfigured', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AddressURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='addressip',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DNSmisconfiguration.AddressURL'),
        ),
    ]
