# Generated by Django 2.0 on 2018-09-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNSmisconfiguration', '0002_auto_20180920_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='knownnameserver',
            unique_together=set(),
        ),
    ]
