# Generated by Django 2.0 on 2018-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNSmisconfiguration', '0004_rootdnsservers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_dict', models.BinaryField()),
            ],
        ),
    ]
