# Generated by Django 2.0 on 2018-09-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNSmisconfiguration', '0005_storeddict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeddict',
            old_name='json_dict',
            new_name='pickle_dict',
        ),
    ]
